name: Deploy to Robocorp Control Room

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Install Robocorp CLI
        run: pip install rpaframework

      - name: Pack Robocorp robot
        run: rcc task pack

      - name: Deploy to Robocorp Control Room
        env:
          RCC_API_KEY: ${{ secrets.ROBOLAB_API_KEY }}
          RCC_WORKSPACE_ID: ${{ secrets.ROBOLAB_WORKSPACE_ID }}
        run: rcc cloud push --workspace $RCC_WORKSPACE_ID --process $RCC_API_KEY
